### ISSUE TITLE
[API] Get user count grouped by gender and time

### ISSUE THREAD

**Issue by raquelguimaraes** [aninhalacerda/women-contributing#4]
```
{
“2014”:
     {“01”: {“F”:10, ”M”:20}
      … 
     }
}
```

**Comment by aninhalacerda** [comment]
The output is :

[ { _id : { year : 2014, month : 3, gender : 'female' }, count : 1 }, 
  { _id : { year : 2014, month : 3, gender : 'male' }, count : 1 }, 
  { _id : { year : 2014, month : 2, gender : 'male' }, count : 1 }, 
  { _id : { year : 2014, month : 1, gender : 'female' }, count : 1 }  ]
