### ISSUE TITLE
Tests aren't running properly

### ISSUE THREAD

**Issue by aninhalacerda** [aninhalacerda/women-contributing#6]
Every time we run ``jasmine-node spec`` not all the test are running, and always the same result is shown:

``..$``

Even if you change any test to make it fail.

**Comment by aninhalacerda** [comment]
It was a problem with 'sort' option on user group.

Tests are running now but not passing :(

**Comment by raquelguimaraes** [comment]
Pushed some changes that fixed the build.. It was not pretty :(
